



export default Screens = {
    "MAIN_MENU": "MAIN_MENU",
    "HAPY_PLACES": "HAPY_PLACES",
    "LOGIN": "LOGIN",
    "FAQ": "FAQ",
    "ABOUT": "ABOUT",
    "FAVORITE_PLACES": "FAVORITE_PLACES",
    "SOFTWARE_INFO": "SOFTWARE_INFO",
    "REGISTER_HAPPY_PLACE": "REGISTER_HAPPY_PLACE",
    "REGISTER_USER": "REGISTER_USER",
}

