



export default Screens = {
    "MAIN_MENU": "MAIN_MENU",
    "MAP_SCREEN": "MAP_SCREEN",
    "LOGIN": "LOGIN",
    "APP_INFO": "APP_INFO",
    "FAVORITE_PLACES": "FAVORITE_PLACES",
    "SOFTWARE_INFO": "SOFTWARE_INFO",
    "REGISTER_HAPPY_PLACE": "REGISTER_HAPPY_PLACE",
    "REGISTER_USER": "REGISTER_USER",
}

